version: '3.6'
services:
  postgres:
    image: postgres:10.5
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - 5432:5432